export const api_Key = `2f9ab31c77bdc9df05bc94c7c4ac3e16`;
export const api_Trending = `https://api.themoviedb.org/3/discover/tv?api_key=${api_Key}&language=en-US&sort_by=popularity.desc&page=1&timezone=America%2FNew_York&with_networks=213&include_null_first_air_dates=false&with_watch_monetization_types=flatrate`;
export const api_Top20today = `https://api.themoviedb.org/3/trending/all/day?api_key=${api_Key}`;
export const api_Tvthrillers = `https://api.themoviedb.org/3/tv/popular?api_key=${api_Key}&language=en-US&page=1`;
export const api_ActionandAdventure = `https://api.themoviedb.org/3/discover/movie?api_key=${api_Key}&language=en-US&sort_by=popularity.desc&page=1&with_genres=28%2C12&with_watch_monetization_types=flatrate`;
export const api_UsTvShows = `https://api.themoviedb.org/3/discover/tv?api_key=${api_Key}&language=en-US&sort_by=popularity.desc&page=1&timezone=America%2FNew_York&include_null_first_air_dates=false&with_watch_providers=8&watch_region=US&with_watch_monetization_types=flatrate`;
export const api_Img = `https://image.tmdb.org/t/p/original`;
export const api_Movie = `https://api.themoviedb.org/3/movie/`;
export const api_Tv = `https://api.themoviedb.org/3/tv/`;
